/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analytics/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registra evento interno de analytics do frontend sem PII. Usuário e papel são derivados da sessão autenticada. */
        post: operations["analytics_events_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada de materiais ativos com saldo disponível calculado. Retorna apenas materiais com is_active=True. */
        get: operations["materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detalha um material ativo pelo identificador, incluindo o saldo disponível calculado. */
        get: operations["materials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada das notificações visíveis ao usuário autenticado. Inclui notificações individuais do usuário e notificações coletivas do papel atual. */
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/mark-read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications_mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retorna configuração pública de Web Push para o usuário autenticado. */
        get: operations["notifications_push_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registra evento técnico sem PII sobre suporte, permissão ou badge de Web Push. Limitado a 20 chamadas por minuto por usuário autenticado. */
        post: operations["notifications_push_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscriptions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registra ou atualiza a assinatura Web Push do usuário autenticado. */
        post: operations["notifications_push_subscriptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscriptions/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Desativa uma assinatura Web Push do usuário autenticado pelo endpoint. */
        post: operations["notifications_push_subscriptions_deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retorna o contador de notificações individuais não lidas do usuário autenticado. Notificações coletivas por papel não entram nesse contador. */
        get: operations["notifications_unread_count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada das requisições visíveis ao usuário autenticado. Suporta busca textual simples e filtro por status. */
        get: operations["requisitions_list"];
        put?: never;
        post: operations["requisitions_create_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detalhe canônico de uma requisição visível ao usuário autenticado, incluindo itens e resumo operacional da timeline. */
        get: operations["requisitions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/authorize/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/discard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["requisitions_discard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["requisitions_update_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/fulfill/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_fulfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/pickup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_pickup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/refuse/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_refuse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/return-to-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_return_to_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada das requisições pessoais do usuário autenticado. Inclui apenas requisições em que o usuário é criador ou beneficiário. */
        get: operations["requisitions_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/pending-approvals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["requisitions_pending_approvals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/pending-fulfillments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["requisitions_pending_fulfillments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/beneficiary-lookup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_beneficiary_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginInput: {
            matricula_funcional: string;
            password: string;
        };
        AuthSessionOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
            readonly papel: string;
            readonly setor: components["schemas"]["AuthSetorOutput"] | null;
            readonly is_authenticated: boolean;
        };
        AuthSetorOutput: {
            readonly id: number;
            readonly nome: string;
        };
        BeneficiaryLookupOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
            readonly setor: components["schemas"]["AuthSetorOutput"];
        };
        /** @enum {unknown} */
        BlankEnum: "";
        CsrfTokenOutput: {
            readonly csrf_token: string;
        };
        /**
         * @description * `ativo` - Ativo
         *     * `bloqueado` - Bloqueado
         *     * `sem_suporte` - Sem suporte
         *     * `requer_instalacao_pwa` - Requer instalação PWA
         *     * `requer_ativacao` - Requer ativação
         * @enum {string}
         */
        DiagnosticStatusEnum: "ativo" | "bloqueado" | "sem_suporte" | "requer_instalacao_pwa" | "requer_ativacao";
        /**
         * @description * `beneficiario` - Beneficiário
         *     * `itens` - Itens
         *     * `revisao` - Revisão
         *     * `envio` - Envio
         * @enum {string}
         */
        DraftStepEnum: "beneficiario" | "itens" | "revisao" | "envio";
        ErrorDetail: {
            code: string;
            message: string;
            details?: unknown;
            trace_id?: string | null;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        FrontendAnalyticsEventInput: {
            event_type: components["schemas"]["FrontendAnalyticsEventTypeEnum"];
            screen?: components["schemas"]["ScreenEnum"] | components["schemas"]["BlankEnum"];
            draft_step?: components["schemas"]["DraftStepEnum"] | components["schemas"]["BlankEnum"];
            action?: string;
            endpoint_key?: string;
            http_status?: number;
            error_code?: string;
            trace_id?: string;
        };
        FrontendAnalyticsEventOutput: {
            readonly event_type: components["schemas"]["FrontendAnalyticsEventTypeEnum"];
            readonly screen: components["schemas"]["ScreenEnum"];
            readonly draft_step: components["schemas"]["DraftStepEnum"];
            readonly action: string;
            readonly endpoint_key: string;
            readonly http_status: number | null;
            readonly error_code: string;
            readonly trace_id: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `login_success` - Login realizado
         *     * `draft_started` - Criação iniciada
         *     * `draft_saved` - Rascunho salvo
         *     * `draft_submitted` - Rascunho enviado
         *     * `draft_abandoned` - Rascunho abandonado
         *     * `authorization_total` - Autorização total
         *     * `authorization_partial` - Autorização parcial
         *     * `authorization_refused` - Autorização recusada
         *     * `api_error` - Erro de API
         * @enum {string}
         */
        FrontendAnalyticsEventTypeEnum: "login_success" | "draft_started" | "draft_saved" | "draft_submitted" | "draft_abandoned" | "authorization_total" | "authorization_partial" | "authorization_refused" | "api_error";
        /**
         * @description Serializer para listagem de materiais disponíveis.
         *
         *     Campo saldo_disponivel é calculado dinamicamente (saldo_fisico - saldo_reservado).
         *     Bloqueios por saldo insuficiente ou divergência crítica são validados na criação da requisição.
         */
        MaterialListOutput: {
            readonly id: number;
            /** @description Código completo xxx.yyy.zzz do material no SCPI */
            readonly codigo_completo: string;
            /** @description Nome descritivo vindo do SCPI */
            readonly nome: string;
            /** @description Descrição vinda do SCPI */
            readonly descricao: string;
            /** @description Unidade de medida vinda do SCPI */
            readonly unidade_medida: string;
            /**
             * Format: double
             * @description Retorna saldo_disponivel do EstoqueMaterial associado, ou None se não existir.
             */
            readonly saldo_disponivel: number | null;
        };
        /** @description Envelope paginado padrão para listagem de materiais. */
        MaterialListPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["MaterialListOutput"][];
        };
        NotificacaoDestinoOutput: {
            readonly tipo: components["schemas"]["NotificacaoDestinoOutputTipoEnum"];
            readonly usuario_id: number | null;
            readonly papel: string | null;
        };
        /**
         * @description * `usuario` - usuario
         *     * `papel` - papel
         * @enum {string}
         */
        NotificacaoDestinoOutputTipoEnum: "usuario" | "papel";
        NotificacaoListPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["NotificacaoOutput"][];
        };
        NotificacaoObjetoRelacionadoOutput: {
            readonly tipo: string;
            readonly id: number;
            readonly numero_publico: string | null;
            readonly status: string;
        };
        NotificacaoOutput: {
            readonly id: number;
            /**
             * @description Tipo de notificação.
             *
             *     * `requisicao_enviada_autorizacao` - Requisição enviada para autorização
             *     * `requisicao_autorizada` - Requisição autorizada
             *     * `requisicao_recusada` - Requisição recusada
             *     * `requisicao_cancelada` - Requisição cancelada
             *     * `requisicao_pronta_para_retirada` - Requisição pronta para retirada
             *     * `requisicao_retirada` - Requisição retirada
             */
            readonly tipo: components["schemas"]["NotificacaoOutputTipoEnum"];
            readonly titulo: string;
            readonly mensagem: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly lida: boolean;
            /** Format: date-time */
            readonly lida_em: string | null;
            readonly leitura_suportada: boolean;
            readonly destino: components["schemas"]["NotificacaoDestinoOutput"];
            readonly objeto_relacionado: components["schemas"]["NotificacaoObjetoRelacionadoOutput"] | null;
        };
        /**
         * @description * `requisicao_enviada_autorizacao` - Requisição enviada para autorização
         *     * `requisicao_autorizada` - Requisição autorizada
         *     * `requisicao_recusada` - Requisição recusada
         *     * `requisicao_cancelada` - Requisição cancelada
         *     * `requisicao_pronta_para_retirada` - Requisição pronta para retirada
         *     * `requisicao_retirada` - Requisição retirada
         * @enum {string}
         */
        NotificacaoOutputTipoEnum: "requisicao_enviada_autorizacao" | "requisicao_autorizada" | "requisicao_recusada" | "requisicao_cancelada" | "requisicao_pronta_para_retirada" | "requisicao_retirada";
        NotificacaoUnreadCountOutput: {
            readonly unread_count: number;
        };
        PushClientEventInput: {
            event_type: components["schemas"]["PushClientEventTypeEnum"];
            diagnostic_status: components["schemas"]["DiagnosticStatusEnum"];
            notification_supported: boolean;
            service_worker_supported: boolean;
            push_manager_supported: boolean;
            badging_supported: boolean;
            standalone_display: boolean;
        };
        PushClientEventOutput: {
            readonly event_type: components["schemas"]["PushClientEventTypeEnum"];
            readonly diagnostic_status: components["schemas"]["DiagnosticStatusEnum"];
            readonly notification_supported: boolean;
            readonly service_worker_supported: boolean;
            readonly push_manager_supported: boolean;
            readonly badging_supported: boolean;
            readonly standalone_display: boolean;
            /** Format: date */
            readonly event_date: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `push_permission_denied` - Push negado
         *     * `push_unavailable` - Push indisponível
         *     * `push_requires_pwa` - Push requer PWA instalado
         *     * `push_badge_unavailable` - Badge indisponível
         * @enum {string}
         */
        PushClientEventTypeEnum: "push_permission_denied" | "push_unavailable" | "push_requires_pwa" | "push_badge_unavailable";
        PushConfigOutput: {
            readonly enabled: boolean;
            readonly vapid_public_key: string;
        };
        PushSubscriptionDeactivateInput: {
            /** Format: uri */
            endpoint: string;
        };
        PushSubscriptionInput: {
            /** Format: uri */
            endpoint: string;
            keys: components["schemas"]["PushSubscriptionKeysInput"];
        };
        PushSubscriptionKeysInput: {
            p256dh: string;
            auth: string;
        };
        PushSubscriptionOutput: {
            /**
             * Format: uri
             * @description Endpoint retornado pelo PushManager do navegador.
             */
            readonly endpoint: string;
            readonly active: boolean;
        };
        RequisicaoActionOutput: {
            readonly id: number;
            readonly material: components["schemas"]["RequisicaoMaterialOutput"];
            /** @description Unidade de medida (snapshot do material no momento da criação) */
            readonly unidade_medida: string;
            /**
             * Format: decimal
             * @description Quantidade solicitada
             */
            readonly quantidade_solicitada: string;
            /**
             * Format: decimal
             * @description Quantidade autorizada
             */
            readonly quantidade_autorizada: string;
            /**
             * Format: decimal
             * @description Quantidade efetivamente entregue
             */
            readonly quantidade_entregue: string;
            /** @description Justificativa se autorizado em quantidade menor que solicitado */
            readonly justificativa_autorizacao_parcial: string;
            /** @description Justificativa se entregue em quantidade menor que autorizado */
            readonly justificativa_atendimento_parcial: string;
            /** @description Observações sobre o item */
            readonly observacao: string;
        };
        RequisicaoAuthorizeInput: {
            itens: components["schemas"]["RequisicaoItemAuthorizeInput"][];
        };
        RequisicaoCancelInput: {
            /** @default  */
            motivo_cancelamento: string;
        };
        RequisicaoCreateInput: {
            beneficiario_id: number;
            /** @default  */
            observacao: string;
            itens: components["schemas"]["RequisicaoItemCreateInput"][];
        };
        RequisicaoDetailOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `pronta_para_retirada_parcial` - Pronta para Retirada (Parcial)
             *     * `pronta_para_retirada` - Pronta para Retirada
             *     * `retirada` - Retirada
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly chefe_autorizador: components["schemas"]["RequisicaoUserOutput"];
            readonly responsavel_atendimento: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data e hora de criação da requisição
             */
            readonly data_criacao: string;
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            /** @description Motivo da recusa (obrigatório quando status=recusada) */
            readonly motivo_recusa: string;
            /** @description Motivo do cancelamento (obrigatório quando cancelada) */
            readonly motivo_cancelamento: string;
            /**
             * Format: date-time
             * @description Data de finalização ou cancelamento
             */
            readonly data_finalizacao: string | null;
            /** @description Nome de quem retirou (diferente do beneficiário) */
            readonly retirante_fisico: string;
            /**
             * Format: date-time
             * @description Data e hora da retirada física dos materiais
             */
            readonly data_retirada: string | null;
            /** @description Observações gerais */
            readonly observacao: string;
            /** @description Observações gerais do atendimento */
            readonly observacao_atendimento: string;
            readonly itens: components["schemas"]["RequisicaoActionOutput"][];
            readonly eventos: components["schemas"]["RequisicaoTimelineEventOutput"][];
        };
        RequisicaoFulfillInput: {
            /** @default  */
            observacao_atendimento: string;
            itens?: components["schemas"]["RequisicaoItemFulfillInput"][];
        };
        RequisicaoItemAuthorizeInput: {
            item_id: number;
            /** Format: decimal */
            quantidade_autorizada: string;
            /** @default  */
            justificativa_autorizacao_parcial: string;
        };
        RequisicaoItemCreateInput: {
            material_id: number;
            /** Format: decimal */
            quantidade_solicitada: string;
            /** @default  */
            observacao: string;
        };
        RequisicaoItemFulfillInput: {
            item_id: number;
            /** Format: decimal */
            quantidade_entregue: string;
            /** @default  */
            justificativa_atendimento_parcial: string;
        };
        RequisicaoListOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `pronta_para_retirada_parcial` - Pronta para Retirada (Parcial)
             *     * `pronta_para_retirada` - Pronta para Retirada
             *     * `retirada` - Retirada
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            /**
             * Format: date-time
             * @description Data e hora de criação da requisição
             */
            readonly data_criacao: string;
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            /**
             * Format: date-time
             * @description Data de finalização ou cancelamento
             */
            readonly data_finalizacao: string | null;
            /** Format: date-time */
            readonly updated_at: string;
            readonly total_itens: number;
        };
        RequisicaoListPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoListOutput"][];
        };
        RequisicaoMaterialOutput: {
            readonly id: number;
            readonly codigo_completo: string;
            readonly nome: string;
            readonly unidade_medida: string;
        };
        RequisicaoPendingApprovalOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `pronta_para_retirada_parcial` - Pronta para Retirada (Parcial)
             *     * `pronta_para_retirada` - Pronta para Retirada
             *     * `retirada` - Retirada
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly total_itens: number;
        };
        RequisicaoPendingApprovalPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoPendingApprovalOutput"][];
        };
        RequisicaoPendingFulfillmentOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `pronta_para_retirada_parcial` - Pronta para Retirada (Parcial)
             *     * `pronta_para_retirada` - Pronta para Retirada
             *     * `retirada` - Retirada
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly chefe_autorizador: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            readonly total_itens: number;
        };
        RequisicaoPendingFulfillmentPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoPendingFulfillmentOutput"][];
        };
        RequisicaoPickupInput: {
            retirante_fisico: string;
        };
        RequisicaoRefuseInput: {
            motivo_recusa: string;
        };
        RequisicaoSetorOutput: {
            readonly id: number;
            readonly nome: string;
        };
        RequisicaoTimelineEventOutput: {
            readonly id: number;
            /**
             * @description Tipo de evento registrado
             *
             *     * `criacao` - Criação
             *     * `envio_autorizacao` - Envio para Autorização
             *     * `retorno_rascunho` - Retorno para Rascunho
             *     * `reenvio_autorizacao` - Reenvio para Autorização
             *     * `autorizacao_total` - Autorização Total
             *     * `autorizacao_parcial` - Autorização Parcial
             *     * `recusa` - Recusa
             *     * `atendimento_parcial` - Atendimento Parcial
             *     * `atendimento` - Atendimento
             *     * `retirada` - Retirada
             *     * `cancelamento` - Cancelamento
             *     * `estorno` - Estorno
             */
            readonly tipo_evento: components["schemas"]["TipoEventoEnum"];
            readonly usuario: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data e hora do evento
             */
            readonly data_hora: string;
            /** @description Observações sobre o evento */
            readonly observacao: string;
        };
        RequisicaoUserOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
        };
        /**
         * @description * `login` - Login
         *     * `minhas_requisicoes` - Minhas requisições
         *     * `nova_requisicao` - Nova requisição
         *     * `requisicao_detalhe` - Detalhe da requisição
         *     * `autorizacoes` - Autorizações
         *     * `atendimentos` - Atendimentos
         *     * `alertas` - Alertas
         *     * `shell` - Shell
         * @enum {string}
         */
        ScreenEnum: "login" | "minhas_requisicoes" | "nova_requisicao" | "requisicao_detalhe" | "autorizacoes" | "atendimentos" | "alertas" | "shell";
        /**
         * @description * `rascunho` - Rascunho
         *     * `aguardando_autorizacao` - Aguardando Autorização
         *     * `recusada` - Recusada
         *     * `autorizada` - Autorizada
         *     * `pronta_para_retirada_parcial` - Pronta para Retirada (Parcial)
         *     * `pronta_para_retirada` - Pronta para Retirada
         *     * `retirada` - Retirada
         *     * `cancelada` - Cancelada
         *     * `estornada` - Estornada
         * @enum {string}
         */
        StatusEnum: "rascunho" | "aguardando_autorizacao" | "recusada" | "autorizada" | "pronta_para_retirada_parcial" | "pronta_para_retirada" | "retirada" | "cancelada" | "estornada";
        /**
         * @description * `criacao` - Criação
         *     * `envio_autorizacao` - Envio para Autorização
         *     * `retorno_rascunho` - Retorno para Rascunho
         *     * `reenvio_autorizacao` - Reenvio para Autorização
         *     * `autorizacao_total` - Autorização Total
         *     * `autorizacao_parcial` - Autorização Parcial
         *     * `recusa` - Recusa
         *     * `atendimento_parcial` - Atendimento Parcial
         *     * `atendimento` - Atendimento
         *     * `retirada` - Retirada
         *     * `cancelamento` - Cancelamento
         *     * `estorno` - Estorno
         * @enum {string}
         */
        TipoEventoEnum: "criacao" | "envio_autorizacao" | "retorno_rascunho" | "reenvio_autorizacao" | "autorizacao_total" | "autorizacao_parcial" | "recusa" | "atendimento_parcial" | "atendimento" | "retirada" | "cancelamento" | "estorno";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analytics_events_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontendAnalyticsEventInput"];
                "application/x-www-form-urlencoded": components["schemas"]["FrontendAnalyticsEventInput"];
                "multipart/form-data": components["schemas"]["FrontendAnalyticsEventInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendAnalyticsEventOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenOutput"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginInput"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthLoginInput"];
                "multipart/form-data": components["schemas"]["AuthLoginInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOutput"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOutput"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    materials_list: {
        parameters: {
            query?: {
                /** @description Filtro por código do grupo (ex: 001) */
                grupo?: string;
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
                /** @description Busca textual em: codigo_completo, nome, descricao (case-insensitive) */
                search?: string;
                /** @description Filtro por código do subgrupo (ex: 001) */
                subgrupo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    materials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificacaoListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Notificação. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificacaoOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_push_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfigOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_push_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushClientEventInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PushClientEventInput"];
                "multipart/form-data": components["schemas"]["PushClientEventInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushClientEventOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_push_subscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PushSubscriptionInput"];
                "multipart/form-data": components["schemas"]["PushSubscriptionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_push_subscriptions_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionDeactivateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["PushSubscriptionDeactivateInput"];
                "multipart/form-data": components["schemas"]["PushSubscriptionDeactivateInput"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    notifications_unread_count: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificacaoUnreadCountOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_list: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
                /** @description Busca textual por número público, nome do beneficiário ou nome do criador. */
                search?: string;
                /** @description Filtro exato por status da requisição. */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_create_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoCreateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCreateInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCreateInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_authorize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoAuthorizeInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoAuthorizeInput"];
                "multipart/form-data": components["schemas"]["RequisicaoAuthorizeInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RequisicaoCancelInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCancelInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCancelInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_update_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoCreateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCreateInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCreateInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_fulfill: {
        parameters: {
            query?: never;
            header: {
                /** @description Chave obrigatória para retries seguros do atendimento; escopada por usuário, endpoint, requisição e payload. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RequisicaoFulfillInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoFulfillInput"];
                "multipart/form-data": components["schemas"]["RequisicaoFulfillInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_pickup: {
        parameters: {
            query?: never;
            header: {
                /** @description Chave obrigatória para retries seguros da retirada; escopada por usuário, endpoint, requisição e payload. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoPickupInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoPickupInput"];
                "multipart/form-data": components["schemas"]["RequisicaoPickupInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_refuse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoRefuseInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoRefuseInput"];
                "multipart/form-data": components["schemas"]["RequisicaoRefuseInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_return_to_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_mine: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
                /** @description Busca textual por número público, nome do beneficiário ou nome do criador. */
                search?: string;
                /** @description Filtro exato por status da requisição. */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_pending_approvals: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoPendingApprovalPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_pending_fulfillments: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoPendingFulfillmentPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_beneficiary_lookup: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista curta de beneficiários elegíveis, limitada a 10 resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryLookupOutput"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
