/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada de materiais ativos com saldo disponível calculado. Retorna apenas materiais com is_active=True. */
        get: operations["materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detalha um material ativo pelo identificador, incluindo o saldo disponível calculado. */
        get: operations["materials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista paginada das requisições visíveis ao usuário autenticado. Suporta busca textual simples e filtro por status. */
        get: operations["requisitions_list"];
        put?: never;
        post: operations["requisitions_create_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detalhe canônico de uma requisição visível ao usuário autenticado, incluindo itens e resumo operacional da timeline. */
        get: operations["requisitions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/authorize/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/discard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["requisitions_discard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["requisitions_update_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/fulfill/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_fulfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/refuse/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_refuse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/return-to-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_return_to_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requisitions_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/pending-approvals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["requisitions_pending_approvals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requisitions/pending-fulfillments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["requisitions_pending_fulfillments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/beneficiary-lookup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_beneficiary_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginInput: {
            matricula_funcional: string;
            password: string;
        };
        AuthSessionOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
            readonly papel: string;
            readonly setor: components["schemas"]["AuthSetorOutput"] | null;
            readonly is_authenticated: boolean;
        };
        AuthSetorOutput: {
            readonly id: number;
            readonly nome: string;
        };
        BeneficiaryLookupOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
            readonly setor: components["schemas"]["AuthSetorOutput"];
        };
        CsrfTokenOutput: {
            readonly csrf_token: string;
        };
        ErrorDetail: {
            code: string;
            message: string;
            details?: unknown;
            trace_id?: string | null;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description Serializer para listagem de materiais disponíveis.
         *
         *     Campo saldo_disponivel é calculado dinamicamente (saldo_fisico - saldo_reservado).
         *     Bloqueios por saldo insuficiente ou divergência crítica são validados na criação da requisição.
         */
        MaterialListOutput: {
            readonly id: number;
            /** @description Código completo xxx.yyy.zzz do material no SCPI */
            readonly codigo_completo: string;
            /** @description Nome descritivo vindo do SCPI */
            readonly nome: string;
            /** @description Descrição vinda do SCPI */
            readonly descricao: string;
            /** @description Unidade de medida vinda do SCPI */
            readonly unidade_medida: string;
            /**
             * Format: double
             * @description Retorna saldo_disponivel do EstoqueMaterial associado, ou None se não existir.
             */
            readonly saldo_disponivel: number | null;
        };
        /** @description Envelope paginado padrão para listagem de materiais. */
        MaterialListPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["MaterialListOutput"][];
        };
        RequisicaoActionOutput: {
            readonly id: number;
            readonly material: components["schemas"]["RequisicaoMaterialOutput"];
            /** @description Unidade de medida (snapshot do material no momento da criação) */
            readonly unidade_medida: string;
            /**
             * Format: decimal
             * @description Quantidade solicitada
             */
            readonly quantidade_solicitada: string;
            /**
             * Format: decimal
             * @description Quantidade autorizada
             */
            readonly quantidade_autorizada: string;
            /**
             * Format: decimal
             * @description Quantidade efetivamente entregue
             */
            readonly quantidade_entregue: string;
            /** @description Justificativa se autorizado em quantidade menor que solicitado */
            readonly justificativa_autorizacao_parcial: string;
            /** @description Justificativa se entregue em quantidade menor que autorizado */
            readonly justificativa_atendimento_parcial: string;
            /** @description Observações sobre o item */
            readonly observacao: string;
        };
        RequisicaoAuthorizeInput: {
            itens: components["schemas"]["RequisicaoItemAuthorizeInput"][];
        };
        RequisicaoCancelInput: {
            /** @default  */
            motivo_cancelamento: string;
        };
        RequisicaoCreateInput: {
            beneficiario_id: number;
            /** @default  */
            observacao: string;
            itens: components["schemas"]["RequisicaoItemCreateInput"][];
        };
        RequisicaoDetailOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `atendida_parcialmente` - Atendida Parcialmente
             *     * `atendida` - Atendida
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly chefe_autorizador: components["schemas"]["RequisicaoUserOutput"];
            readonly responsavel_atendimento: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data e hora de criação da requisição
             */
            readonly data_criacao: string;
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            /** @description Motivo da recusa (obrigatório quando status=recusada) */
            readonly motivo_recusa: string;
            /** @description Motivo do cancelamento (obrigatório quando cancelada) */
            readonly motivo_cancelamento: string;
            /**
             * Format: date-time
             * @description Data de finalização ou cancelamento
             */
            readonly data_finalizacao: string | null;
            /** @description Nome de quem retirou (diferente do beneficiário) */
            readonly retirante_fisico: string;
            /** @description Observações gerais */
            readonly observacao: string;
            /** @description Observações gerais do atendimento */
            readonly observacao_atendimento: string;
            readonly itens: components["schemas"]["RequisicaoActionOutput"][];
            readonly eventos: components["schemas"]["RequisicaoTimelineEventOutput"][];
        };
        RequisicaoFulfillInput: {
            /** @default  */
            retirante_fisico: string;
            /** @default  */
            observacao_atendimento: string;
            itens?: components["schemas"]["RequisicaoItemFulfillInput"][];
        };
        RequisicaoItemAuthorizeInput: {
            item_id: number;
            /** Format: decimal */
            quantidade_autorizada: string;
            /** @default  */
            justificativa_autorizacao_parcial: string;
        };
        RequisicaoItemCreateInput: {
            material_id: number;
            /** Format: decimal */
            quantidade_solicitada: string;
            /** @default  */
            observacao: string;
        };
        RequisicaoItemFulfillInput: {
            item_id: number;
            /** Format: decimal */
            quantidade_entregue: string;
            /** @default  */
            justificativa_atendimento_parcial: string;
        };
        RequisicaoListOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `atendida_parcialmente` - Atendida Parcialmente
             *     * `atendida` - Atendida
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            /**
             * Format: date-time
             * @description Data e hora de criação da requisição
             */
            readonly data_criacao: string;
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            /**
             * Format: date-time
             * @description Data de finalização ou cancelamento
             */
            readonly data_finalizacao: string | null;
            /** Format: date-time */
            readonly updated_at: string;
            readonly total_itens: number;
        };
        RequisicaoListPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoListOutput"][];
        };
        RequisicaoMaterialOutput: {
            readonly id: number;
            readonly codigo_completo: string;
            readonly nome: string;
            readonly unidade_medida: string;
        };
        RequisicaoPendingApprovalOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `atendida_parcialmente` - Atendida Parcialmente
             *     * `atendida` - Atendida
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * Format: date-time
             * @description Data do primeiro envio para autorização
             */
            readonly data_envio_autorizacao: string | null;
            readonly criador: components["schemas"]["RequisicaoUserOutput"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly total_itens: number;
        };
        RequisicaoPendingApprovalPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoPendingApprovalOutput"][];
        };
        RequisicaoPendingFulfillmentOutput: {
            readonly id: number;
            /** @description Número público da requisição (formato REQ-AAAA-NNNNNN), atribuído no primeiro envio */
            readonly numero_publico: string | null;
            /**
             * @description Status atual da requisição
             *
             *     * `rascunho` - Rascunho
             *     * `aguardando_autorizacao` - Aguardando Autorização
             *     * `recusada` - Recusada
             *     * `autorizada` - Autorizada
             *     * `atendida_parcialmente` - Atendida Parcialmente
             *     * `atendida` - Atendida
             *     * `cancelada` - Cancelada
             *     * `estornada` - Estornada
             */
            readonly status: components["schemas"]["StatusEnum"];
            readonly beneficiario: components["schemas"]["RequisicaoUserOutput"];
            readonly setor_beneficiario: components["schemas"]["RequisicaoSetorOutput"];
            readonly chefe_autorizador: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data da autorização ou recusa
             */
            readonly data_autorizacao_ou_recusa: string | null;
            readonly total_itens: number;
        };
        RequisicaoPendingFulfillmentPaginated: {
            readonly count: number;
            readonly page: number;
            readonly page_size: number;
            readonly total_pages: number;
            /** Format: uri */
            readonly next: string | null;
            /** Format: uri */
            readonly previous: string | null;
            readonly results: components["schemas"]["RequisicaoPendingFulfillmentOutput"][];
        };
        RequisicaoRefuseInput: {
            motivo_recusa: string;
        };
        RequisicaoSetorOutput: {
            readonly id: number;
            readonly nome: string;
        };
        RequisicaoTimelineEventOutput: {
            readonly id: number;
            /**
             * @description Tipo de evento registrado
             *
             *     * `criacao` - Criação
             *     * `envio_autorizacao` - Envio para Autorização
             *     * `retorno_rascunho` - Retorno para Rascunho
             *     * `reenvio_autorizacao` - Reenvio para Autorização
             *     * `autorizacao_total` - Autorização Total
             *     * `autorizacao_parcial` - Autorização Parcial
             *     * `recusa` - Recusa
             *     * `atendimento_parcial` - Atendimento Parcial
             *     * `atendimento` - Atendimento
             *     * `cancelamento` - Cancelamento
             *     * `estorno` - Estorno
             */
            readonly tipo_evento: components["schemas"]["TipoEventoEnum"];
            readonly usuario: components["schemas"]["RequisicaoUserOutput"];
            /**
             * Format: date-time
             * @description Data e hora do evento
             */
            readonly data_hora: string;
            /** @description Observações sobre o evento */
            readonly observacao: string;
        };
        RequisicaoUserOutput: {
            readonly id: number;
            readonly matricula_funcional: string;
            readonly nome_completo: string;
        };
        /**
         * @description * `rascunho` - Rascunho
         *     * `aguardando_autorizacao` - Aguardando Autorização
         *     * `recusada` - Recusada
         *     * `autorizada` - Autorizada
         *     * `atendida_parcialmente` - Atendida Parcialmente
         *     * `atendida` - Atendida
         *     * `cancelada` - Cancelada
         *     * `estornada` - Estornada
         * @enum {string}
         */
        StatusEnum: "rascunho" | "aguardando_autorizacao" | "recusada" | "autorizada" | "atendida_parcialmente" | "atendida" | "cancelada" | "estornada";
        /**
         * @description * `criacao` - Criação
         *     * `envio_autorizacao` - Envio para Autorização
         *     * `retorno_rascunho` - Retorno para Rascunho
         *     * `reenvio_autorizacao` - Reenvio para Autorização
         *     * `autorizacao_total` - Autorização Total
         *     * `autorizacao_parcial` - Autorização Parcial
         *     * `recusa` - Recusa
         *     * `atendimento_parcial` - Atendimento Parcial
         *     * `atendimento` - Atendimento
         *     * `cancelamento` - Cancelamento
         *     * `estorno` - Estorno
         * @enum {string}
         */
        TipoEventoEnum: "criacao" | "envio_autorizacao" | "retorno_rascunho" | "reenvio_autorizacao" | "autorizacao_total" | "autorizacao_parcial" | "recusa" | "atendimento_parcial" | "atendimento" | "cancelamento" | "estorno";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenOutput"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginInput"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthLoginInput"];
                "multipart/form-data": components["schemas"]["AuthLoginInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOutput"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOutput"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    materials_list: {
        parameters: {
            query?: {
                /** @description Filtro por código do grupo (ex: 001) */
                grupo?: string;
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
                /** @description Busca textual em: codigo_completo, nome, descricao (case-insensitive) */
                search?: string;
                /** @description Filtro por código do subgrupo (ex: 001) */
                subgrupo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    materials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_list: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
                /** @description Busca textual por número público, nome do beneficiário ou nome do criador. */
                search?: string;
                /** @description Filtro exato por status da requisição. */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoListPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_create_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoCreateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCreateInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCreateInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_authorize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoAuthorizeInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoAuthorizeInput"];
                "multipart/form-data": components["schemas"]["RequisicaoAuthorizeInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RequisicaoCancelInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCancelInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCancelInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_update_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoCreateInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoCreateInput"];
                "multipart/form-data": components["schemas"]["RequisicaoCreateInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_fulfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RequisicaoFulfillInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoFulfillInput"];
                "multipart/form-data": components["schemas"]["RequisicaoFulfillInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_refuse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoRefuseInput"];
                "application/x-www-form-urlencoded": components["schemas"]["RequisicaoRefuseInput"];
                "multipart/form-data": components["schemas"]["RequisicaoRefuseInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_return_to_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este Requisição. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoDetailOutput"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_pending_approvals: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoPendingApprovalPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requisitions_pending_fulfillments: {
        parameters: {
            query?: {
                /** @description Número da página (padrão: 1) */
                page?: number;
                /** @description Quantidade de resultados por página (padrão: 20, máximo: 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequisicaoPendingFulfillmentPaginated"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_beneficiary_lookup: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista curta de beneficiários elegíveis, limitada a 10 resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryLookupOutput"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
