/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasRequisicoesRouteImport } from './routes/minhas-requisicoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutorizacoesRouteImport } from './routes/autorizacoes'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequisicoesNovaRouteImport } from './routes/requisicoes/nova'
import { Route as RequisicoesIdRouteImport } from './routes/requisicoes/$id'

const MinhasRequisicoesRoute = MinhasRequisicoesRouteImport.update({
  id: '/minhas-requisicoes',
  path: '/minhas-requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizacoesRoute = AutorizacoesRouteImport.update({
  id: '/autorizacoes',
  path: '/autorizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesNovaRoute = RequisicoesNovaRouteImport.update({
  id: '/requisicoes/nova',
  path: '/requisicoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesIdRoute = RequisicoesIdRouteImport.update({
  id: '/requisicoes/$id',
  path: '/requisicoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/autorizacoes': typeof AutorizacoesRoute
  '/login': typeof LoginRoute
  '/minhas-requisicoes': typeof MinhasRequisicoesRoute
  '/requisicoes/$id': typeof RequisicoesIdRoute
  '/requisicoes/nova': typeof RequisicoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/autorizacoes': typeof AutorizacoesRoute
  '/login': typeof LoginRoute
  '/minhas-requisicoes': typeof MinhasRequisicoesRoute
  '/requisicoes/$id': typeof RequisicoesIdRoute
  '/requisicoes/nova': typeof RequisicoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRoute
  '/autorizacoes': typeof AutorizacoesRoute
  '/login': typeof LoginRoute
  '/minhas-requisicoes': typeof MinhasRequisicoesRoute
  '/requisicoes/$id': typeof RequisicoesIdRoute
  '/requisicoes/nova': typeof RequisicoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimentos'
    | '/autorizacoes'
    | '/login'
    | '/minhas-requisicoes'
    | '/requisicoes/$id'
    | '/requisicoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimentos'
    | '/autorizacoes'
    | '/login'
    | '/minhas-requisicoes'
    | '/requisicoes/$id'
    | '/requisicoes/nova'
  id:
    | '__root__'
    | '/'
    | '/atendimentos'
    | '/autorizacoes'
    | '/login'
    | '/minhas-requisicoes'
    | '/requisicoes/$id'
    | '/requisicoes/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentosRoute: typeof AtendimentosRoute
  AutorizacoesRoute: typeof AutorizacoesRoute
  LoginRoute: typeof LoginRoute
  MinhasRequisicoesRoute: typeof MinhasRequisicoesRoute
  RequisicoesIdRoute: typeof RequisicoesIdRoute
  RequisicoesNovaRoute: typeof RequisicoesNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas-requisicoes': {
      id: '/minhas-requisicoes'
      path: '/minhas-requisicoes'
      fullPath: '/minhas-requisicoes'
      preLoaderRoute: typeof MinhasRequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizacoes': {
      id: '/autorizacoes'
      path: '/autorizacoes'
      fullPath: '/autorizacoes'
      preLoaderRoute: typeof AutorizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes/nova': {
      id: '/requisicoes/nova'
      path: '/requisicoes/nova'
      fullPath: '/requisicoes/nova'
      preLoaderRoute: typeof RequisicoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes/$id': {
      id: '/requisicoes/$id'
      path: '/requisicoes/$id'
      fullPath: '/requisicoes/$id'
      preLoaderRoute: typeof RequisicoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentosRoute: AtendimentosRoute,
  AutorizacoesRoute: AutorizacoesRoute,
  LoginRoute: LoginRoute,
  MinhasRequisicoesRoute: MinhasRequisicoesRoute,
  RequisicoesIdRoute: RequisicoesIdRoute,
  RequisicoesNovaRoute: RequisicoesNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
